version: '3.5'
services:
  petstore-gateway:
    expose:
      - "8080"
    build: .
  petstore-pet:
    expose:
      - "8081"
    build: "../pet-service-v1"
  petstore-user:
    expose:
      - "8082"
    build: "../user-service-v1"
  petstore-store:
    expose:
      - "8083"
    build: "../store-service-v1"
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - petstore-gateway
      - petstore-pet
      - petstore-user
      - petstore-store
    ports:
      - "4000:4000"